//Action types
export const GET_CURRENT_RATE = 'GET_CURRENT_RATE';
export const GET_CURRENT_RATE_PENDING = 'GET_CURRENT_RATE_PENDING';
export const GET_CURRENT_RATE_FULFILLED = 'GET_CURRENT_RATE_FULFILLED';
export const GET_CURRENT_RATE_REJECTED = 'GET_CURRENT_RATE_REJECTED';

export const GET_MONTHLY_RATES = 'GET_MONTHLY_RATES';
export const GET_MONTHLY_RATES_PENDING = 'GET_MONTHLY_RATES_PENDING';
export const GET_MONTHLY_RATES_FULFILLED = 'GET_MONTHLY_RATES_FULFILLED';
export const GET_MONTHLY_RATES_REJECTED = 'GET_MONTHLY_RATES_REJECTED';

export const GET_CURRENCY_CODES = 'GET_CURRENCY_CODES';
export const GET_CURRENCY_CODES_PENDING = 'GET_CURRENCY_CODES_PENDING';
export const GET_CURRENCY_CODES_FULFILLED = 'GET_CURRENCY_CODES_FULFILLED';
export const GET_CURRENCY_CODES_REJECTED = 'GET_CURRENCY_CODES_REJECTED';

export const GET_SUGGESTIONS = 'GET_SUGGESTIONS';

//API
export const COINDESK_API_BASE_URL = 'https://api.coindesk.com/v1/bpi/';
